### ISSUE TITLE
Issues with "rollup.js"

### ISSUE THREAD

**Issue by JJ** [blubitz/cup-readdir#1]
When trying to bundle this module together with others, I gets this error:

```
[!] Error: 'getAllFilePaths' is not exported by ../../core/utils/silly-i18n/node_modules/cup-readdir/index.js, imported by ../../core/utils/silly-i18n/src/index.js
```

which strictly, is totally true. This is probably just a matter of configuring rollup right. However, I'm just leaving it here just in case someone bumps into this in the future, or you have an idea of how to fix it.

**Comment by blubitz** [comment]
I have tried bundling this module with rollup and cannot reproduce the error. 
```shell
rollup index.js --file bundle.js --format iife

index.js → bundle.js...
created bundle.js in 22ms
rollup index.js --file bundle.js --format cjs

index.js → bundle.js...
created bundle.js in 22ms
rollup index.js --file bundle.js --format umd --name "myBundle"

index.js → bundle.js...
created bundle.js in 23ms
```
```js
// index.js
const cupr = require('cup-readdir')

cupr.getAllFilePaths('.').then(paths => {
  console.log(paths)
})
```
Please provide a minimally reproducable test case. Also, this may be more suited as a feature request because compatibility with rollup was not specified in the documentation to begin with.

**Comment by JJ** [comment]
At any rate, using `fs` in the browser is going to need a whole lot of polyfills... Or it's going to be eventually impossible. So it's just as well that it errors with rollup.
